'use strict';
class ElementType {
	public readonly TYPE_META_DATA: number;
	/* #INSERT_GENERATE_ELEMENT_TYPE_DECLARATION# */
	/* <!-- AUTOMATICALLY GENERATED DO NOT EDIT DIRECTLY !--> */
	public readonly TYPE_RESISTOR: number;
	public readonly TYPE_CAPACITOR: number;
	public readonly TYPE_INDUCTOR: number;
	public readonly TYPE_GROUND: number;
	public readonly TYPE_DCSOURCE: number;
	public readonly TYPE_DCCURRENT: number;
	public readonly TYPE_ACSOURCE: number;
	public readonly TYPE_ACCURRENT: number;
	public readonly TYPE_SQUAREWAVE: number;
	public readonly TYPE_SAW: number;
	public readonly TYPE_TRI: number;
	public readonly TYPE_CONSTANT: number;
	public readonly TYPE_WIRE: number;
	public readonly TYPE_NET: number;
	public readonly TYPE_NOTE: number;
	public readonly TYPE_RAIL: number;
	public readonly TYPE_VOLTMETER: number;
	public readonly TYPE_OHMMETER: number;
	public readonly TYPE_AMMETER: number;
	public readonly TYPE_WATTMETER: number;
	public readonly TYPE_FUSE: number;
	public readonly TYPE_SPST: number;
	public readonly TYPE_SPDT: number;
	public readonly TYPE_NOT: number;
	public readonly TYPE_DIODE: number;
	public readonly TYPE_LED: number;
	public readonly TYPE_ZENER: number;
	public readonly TYPE_POTENTIOMETER: number;
	public readonly TYPE_AND: number;
	public readonly TYPE_OR: number;
	public readonly TYPE_NAND: number;
	public readonly TYPE_NOR: number;
	public readonly TYPE_XOR: number;
	public readonly TYPE_XNOR: number;
	public readonly TYPE_DFF: number;
	public readonly TYPE_VSAT: number;
	public readonly TYPE_ADD: number;
	public readonly TYPE_SUB: number;
	public readonly TYPE_MUL: number;
	public readonly TYPE_DIV: number;
	public readonly TYPE_GAIN: number;
	public readonly TYPE_ABS: number;
	public readonly TYPE_VCSW: number;
	public readonly TYPE_VCVS: number;
	public readonly TYPE_VCCS: number;
	public readonly TYPE_CCCS: number;
	public readonly TYPE_CCVS: number;
	public readonly TYPE_OPAMP: number;
	public readonly TYPE_NMOS: number;
	public readonly TYPE_PMOS: number;
	public readonly TYPE_NPN: number;
	public readonly TYPE_PNP: number;
	public readonly TYPE_ADC: number;
	public readonly TYPE_DAC: number;
	public readonly TYPE_SAH: number;
	public readonly TYPE_PWM: number;
	public readonly TYPE_INTEGRATOR: number;
	public readonly TYPE_DIFFERENTIATOR: number;
	public readonly TYPE_LPF: number;
	public readonly TYPE_HPF: number;
	public readonly TYPE_REL: number;
	public readonly TYPE_PID: number;
	public readonly TYPE_LUT: number;
	public readonly TYPE_VCR: number;
	public readonly TYPE_VCCA: number;
	public readonly TYPE_VCL: number;
	public readonly TYPE_GRT: number;
	public readonly TYPE_TPTZ: number;
	public readonly TYPE_TRAN: number;
	/* <!-- END AUTOMATICALLY GENERATED !--> */
	constructor() {
		this.TYPE_META_DATA = -2;
		let type_counter: number = 0;
		/* #INSERT_GENERATE_ELEMENT_TYPE# */
		/* <!-- AUTOMATICALLY GENERATED DO NOT EDIT DIRECTLY !--> */
		this.TYPE_RESISTOR = type_counter++;
		this.TYPE_CAPACITOR = type_counter++;
		this.TYPE_INDUCTOR = type_counter++;
		this.TYPE_GROUND = type_counter++;
		this.TYPE_DCSOURCE = type_counter++;
		this.TYPE_DCCURRENT = type_counter++;
		this.TYPE_ACSOURCE = type_counter++;
		this.TYPE_ACCURRENT = type_counter++;
		this.TYPE_SQUAREWAVE = type_counter++;
		this.TYPE_SAW = type_counter++;
		this.TYPE_TRI = type_counter++;
		this.TYPE_CONSTANT = type_counter++;
		this.TYPE_WIRE = type_counter++;
		this.TYPE_NET = type_counter++;
		this.TYPE_NOTE = type_counter++;
		this.TYPE_RAIL = type_counter++;
		this.TYPE_VOLTMETER = type_counter++;
		this.TYPE_OHMMETER = type_counter++;
		this.TYPE_AMMETER = type_counter++;
		this.TYPE_WATTMETER = type_counter++;
		this.TYPE_FUSE = type_counter++;
		this.TYPE_SPST = type_counter++;
		this.TYPE_SPDT = type_counter++;
		this.TYPE_NOT = type_counter++;
		this.TYPE_DIODE = type_counter++;
		this.TYPE_LED = type_counter++;
		this.TYPE_ZENER = type_counter++;
		this.TYPE_POTENTIOMETER = type_counter++;
		this.TYPE_AND = type_counter++;
		this.TYPE_OR = type_counter++;
		this.TYPE_NAND = type_counter++;
		this.TYPE_NOR = type_counter++;
		this.TYPE_XOR = type_counter++;
		this.TYPE_XNOR = type_counter++;
		this.TYPE_DFF = type_counter++;
		this.TYPE_VSAT = type_counter++;
		this.TYPE_ADD = type_counter++;
		this.TYPE_SUB = type_counter++;
		this.TYPE_MUL = type_counter++;
		this.TYPE_DIV = type_counter++;
		this.TYPE_GAIN = type_counter++;
		this.TYPE_ABS = type_counter++;
		this.TYPE_VCSW = type_counter++;
		this.TYPE_VCVS = type_counter++;
		this.TYPE_VCCS = type_counter++;
		this.TYPE_CCCS = type_counter++;
		this.TYPE_CCVS = type_counter++;
		this.TYPE_OPAMP = type_counter++;
		this.TYPE_NMOS = type_counter++;
		this.TYPE_PMOS = type_counter++;
		this.TYPE_NPN = type_counter++;
		this.TYPE_PNP = type_counter++;
		this.TYPE_ADC = type_counter++;
		this.TYPE_DAC = type_counter++;
		this.TYPE_SAH = type_counter++;
		this.TYPE_PWM = type_counter++;
		this.TYPE_INTEGRATOR = type_counter++;
		this.TYPE_DIFFERENTIATOR = type_counter++;
		this.TYPE_LPF = type_counter++;
		this.TYPE_HPF = type_counter++;
		this.TYPE_REL = type_counter++;
		this.TYPE_PID = type_counter++;
		this.TYPE_LUT = type_counter++;
		this.TYPE_VCR = type_counter++;
		this.TYPE_VCCA = type_counter++;
		this.TYPE_VCL = type_counter++;
		this.TYPE_GRT = type_counter++;
		this.TYPE_TPTZ = type_counter++;
		this.TYPE_TRAN = type_counter++;
		/* <!-- END AUTOMATICALLY GENERATED !--> */
	}
}
